### ISSUE TITLE
ArgumentNullException

### ISSUE THREAD

**Issue by Crusader2010** [emipa606/NPDTiers#4]
Hi,

I'm getting an error in the log and it seems to be from this mod: https://gist.github.com/HugsLibRecordKeeper/9c325476d15461fab16e3aa6dc830161 (last one at the end)

One of my pawns just harvested a bunch of healroot from a growing area. Also, i'm using around 400 mods so it's quite impossible to check for incompatibilities (nothing that affects healroot though; using Growing Zones+, Dubs mint menus, too).

Thanks

**Comment by emipa606** [comment]
You also have errors from AllowTool, VFETribals, Fluffy Blueprints as well as a lot of earlier errors. There is nothing to say what your issue is here. If you can replicate the error with only this mod loaded I can take a look.
